### PR TITLE
starter layout with search form and history

### PR DESCRIPTION
**Pull request by Jachaplin**

### CODE REVIEW

**Comment by paulrld** [comment]
Great! I like how each input is standardized in name. artist-name-input, song-input, etc.  I had a problem trying to switch to the the html_layout branch to view the html. Git: cannot checkout branch - error: pathspec '…' did not match any file(s) known to git. Found I had to run " git fetch " to update my local repository with the new infor from GitHub. Then I ran git checkout html_layout.

**Comment by Jachaplin** [comment]
Sweet! Glad you like it. That's good to know about the git fetch function. I'll wait to see what Ryan thinks then I'll make the merge.

**Comment by Jachaplin** [comment]
I just updated this branch. This layout only has on search input. Will this cause issues with the api's when a user searches for a song and artist in the same input?

**Comment by paulrld** [comment]
I checked out the html_layout branch. For clarification, the single search will do everything: search for a song, search for an artist, search for year, and album? I like how using a single search saves space on the screen. Will it limit some functionality for the user? Like what if a user wants to search for a song with a specific year? How would a user go about ?

**Comment by Jachaplin** [comment]
I'm not sure if it will limit the user search. Maybe that will be a good thing to test out in today's class. Stoked you can make it!

**Pull request merged**
